<a href="https://colab.research.google.com/github/RAKHISHAKYA/iris-flower-prediction-project/blob/main/Credit_Card_Fraud_Detection_Copy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Business Understanding**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
from pylab import rcParams
rcParams['figure.figsize']=14,8
RANDOM_SEED=42
LABELS=["Normal","Fraud"]

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
pwd()

'/content'

In [7]:
df=pd.read_csv("/content/creditcard.csv")

In [8]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [9]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
154616,102213.0,-2.881177,3.042352,-2.037665,-2.067920,1.730641,-0.563490,1.903018,-0.768910,3.824377,...,-0.551010,0.444579,-0.285562,-0.282634,0.313974,-0.020883,0.758800,-0.037270,0.92,0.0
154617,102215.0,-0.375306,0.532730,0.418723,-1.287062,2.497517,4.122187,-0.287799,1.051660,1.371592,...,-0.272822,-0.576719,-0.039171,0.603659,-0.315255,-0.548130,0.152472,0.134190,4.99,0.0
154618,102227.0,2.026881,-0.097897,-0.738827,0.234993,-0.148646,-0.677590,-0.269752,-0.135180,1.710316,...,-0.586819,-1.534632,0.521472,-0.470581,-0.761147,-0.015124,-0.104300,-0.069280,6.04,0.0
154619,102229.0,-0.099578,1.072275,-1.153646,0.116668,1.755453,1.663162,0.414888,0.515391,-0.042438,...,0.158546,0.861983,-0.007750,-1.217354,-0.874381,1.800225,0.014189,0.089533,24.99,0.0
154620,102233.0,1.502475,-0.122551,-0.002615,3.722850,0.534492,2.229096,-0.735919,0.566677,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.shape

(154621, 31)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154621 entries, 0 to 154620
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    154621 non-null  float64
 1   V1      154621 non-null  float64
 2   V2      154621 non-null  float64
 3   V3      154621 non-null  float64
 4   V4      154621 non-null  float64
 5   V5      154621 non-null  float64
 6   V6      154621 non-null  float64
 7   V7      154621 non-null  float64
 8   V8      154621 non-null  float64
 9   V9      154620 non-null  float64
 10  V10     154620 non-null  float64
 11  V11     154620 non-null  float64
 12  V12     154620 non-null  float64
 13  V13     154620 non-null  float64
 14  V14     154620 non-null  float64
 15  V15     154620 non-null  float64
 16  V16     154620 non-null  float64
 17  V17     154620 non-null  float64
 18  V18     154620 non-null  float64
 19  V19     154620 non-null  float64
 20  V20     154620 non-null  float64
 21  V21     154620 non-null  float64
 22  V22     154620 non-null  float64
 23  V23     154620 non-null  float64
 24  V24     154620 non-null  float64
 25  V25     154620 non-null  float64
 26  V26     154620 non-null  float64
 27  V27     154620 non-null  float64
 28  V28     154620 non-null  float64
 29  Amount  154620 non-null  float64
 30  Class   154620 non-null  float64
dtypes: float64(31)
memory usage: 36.6 MB

In [12]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [13]:
df.isnull().values.any()

True

In [ ]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
#seperating data for analysis
legit= df[df.Class ==0]
fraud= df[df.Class ==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [ ]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
#compare values for both transections
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

# sampling

In [ ]:
#build a sample dataset containing similar distribution of normal transaction and fraudulent transaction
legit_sample =legit.sample(n=492)

In [ ]:
#conactinating two data frames
new_df =pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
274749,166186.0,0.054232,0.839281,0.224720,-0.616528,0.448176,-1.047817,0.989607,-0.180338,0.013487,...,-0.273702,-0.624446,0.056027,-0.125994,-0.480153,0.148487,0.244801,0.095255,3.56,0
151740,96155.0,2.103001,0.037465,-2.144641,0.069134,0.633150,-1.226609,0.519687,-0.439568,1.501528,...,0.006583,0.280834,-0.092216,-0.537324,0.390886,0.215949,-0.129711,-0.101651,15.00,0
135040,81081.0,-0.674672,0.830752,0.779273,-1.681604,-0.203831,-0.884515,0.468578,-0.034466,0.470192,...,-0.007286,0.143112,0.057744,0.136160,-0.570985,-0.152535,-0.370027,-0.145933,5.04,0
73707,55244.0,-0.652814,-0.399088,2.684722,-1.112171,-1.179403,0.417375,-0.350072,0.298090,-0.104068,...,0.073512,0.494416,-0.017259,0.452864,-0.035525,-0.360700,0.152396,0.121905,56.87,0
200575,133489.0,2.105033,-0.169138,-1.862560,-0.026685,0.621089,-0.214157,0.106914,-0.154306,0.262429,...,0.337454,1.159511,-0.163286,0.214063,0.422981,0.994507,-0.102781,-0.088824,2.92,0

In [ ]:
new_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [ ]:
new_df['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [ ]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96097.796748,0.016675,-0.065622,0.020186,0.050326,0.056254,0.016394,0.083408,0.018215,-0.009093,...,-0.003378,-0.035165,-0.008271,0.083144,-0.038455,-0.006101,-0.020014,-0.023936,-0.010711,93.592744
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [ ]:
#splitting the data into feature and targets
X=new_df.drop(columns='Class', axis=1)
Y=new_df['Class']

In [ ]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
274749  166186.0  0.054232  0.839281  0.224720 -0.616528  0.448176 -1.047817
151740   96155.0  2.103001  0.037465 -2.144641  0.069134  0.633150 -1.226609
135040   81081.0 -0.674672  0.830752  0.779273 -1.681604 -0.203831 -0.884515
73707    55244.0 -0.652814 -0.399088  2.684722 -1.112171 -1.179403  0.417375
200575  133489.0  2.105033 -0.169138 -1.862560 -0.026685  0.621089 -0.214157
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
274749  0.989607 -0.180338  0.013487  ... -0.053559 -0.273702 -0.624446
151740  0.519687 -0.439568  1.501528  ... -0.341256  0.006583  0.280834
135040  0.468578 -0.034466  0.470192  ... -0.031783 -0.007286  0.143112
73707  -0.350072  0.298090 -0.104068  ...  0.131334  0.073512  0.494416
200575  0.106914 -0.154306  0.262429  ... -0.150789  0.337454  1.159511
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
274749  0.056027 -0.125994 -0.480153  0.148487  0.244801  0.095255    3.56
151740 -0.092216 -0.537324  0.390886  0.215949 -0.129711 -0.101651   15.00
135040  0.057744  0.136160 -0.570985 -0.152535 -0.370027 -0.145933    5.04
73707  -0.017259  0.452864 -0.035525 -0.360700  0.152396  0.121905   56.87
200575 -0.163286  0.214063  0.422981  0.994507 -0.102781 -0.088824    2.92
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [ ]:
print(Y)

274749    0
151740    0
135040    0
73707     0
200575    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#split the data into training and test data
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.2,stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape , X_test.shape)

(984, 30) (787, 30) (197, 30)

In [ ]:
print(Y.shape, Y_train.shape , Y_test.shape)

(984,) (787,) (197,)

# Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train, Y_train)

LogisticRegression()

# Model Evaluation

In [ ]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction , Y_train)

In [ ]:
print(training_data_accuracy )

0.9479034307496823

In [ ]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction , Y_test)

In [ ]:
print(test_data_accuracy)

0.949238578680203